version: 2
jobs:
  build:
    docker:
      - image: node:12.14.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - run: npm rebuild node-sass
      - run: npm install react-scripts --save

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests and build!
      - run: npm test
      - run: CI=false npm run build
